# Generated by Django 4.2.13 on 2024-05-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_productinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='order',
        ),
    ]
