# Generated by Django 4.2.13 on 2024-05-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0005_remove_productinstance_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'permissions': (('can_mark_issued', 'Set product as issued'),)},
        ),
    ]
