# Generated by Django 4.2.13 on 2024-05-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0007_vacation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="posted_date",
        ),
    ]
