# Generated by Django 4.2.13 on 2024-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0009_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(),
        ),
    ]
