# Generated by Django 4.2.13 on 2024-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0012_remove_order_products_order_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("work_hours", models.CharField(max_length=100)),
            ],
        ),
    ]
