# Generated by Django 4.2.13 on 2024-05-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0013_pickuppoint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
