# Generated by Django 4.2.13 on 2024-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0017_order_address_order_name_order_phone_order_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="address",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="surname",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
