# Generated by Django 4.2.13 on 2024-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0019_coupon_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("image", models.ImageField(upload_to="news_images/")),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
