# Generated by Django 4.2.13 on 2024-06-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0021_faq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.AlterModelOptions(
            name="vacation",
            options={},
        ),
        migrations.DeleteModel(
            name="ProductInstance",
        ),
    ]
