# Generated by Django 4.2.13 on 2024-06-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0023_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
