# Generated by Django 4.2.13 on 2024-06-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0024_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("date_birthday", models.CharField(max_length=255)),
            ],
        ),
    ]
