# Generated by Django 4.2.13 on 2024-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0026_clientdata_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdata",
            name="date_birthday",
            field=models.DateTimeField(max_length=255),
        ),
    ]
